-- drop database bibliot_db;
-- create database Bibliot_DB;
-- use Bibliot_DB;

-- CREATE TABLE Usuarios (
--     ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     nombres VARCHAR(100) NOT NULL,
--     apellidos VARCHAR(100) NOT NULL,
--     correo VARCHAR(100) NOT NULL UNIQUE,
--     contrasena VARCHAR(100) NOT NULL
-- );
